# Generated by Django 3.1.1 on 2020-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizesvariations',
            options={'verbose_name_plural': 'Sizes Variations'},
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
