# Generated by Django 3.1.1 on 2020-09-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200909_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
