# Generated by Django 3.1.1 on 2020-09-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200909_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='size',
            name='size_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
