# Generated by Django 3.1.1 on 2020-09-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200909_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('size_order',)},
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_num',
            new_name='size_order',
        ),
    ]
