# Generated by Django 3.1.1 on 2020-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200910_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Please type price in integer eq. 12.50 PLN -> 1250 PLN'),
        ),
    ]
