# Generated by Django 3.1.1 on 2020-09-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200910_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizesVariations',
            new_name='SizeVariations',
        ),
    ]
