# Generated by Django 3.1.1 on 2020-09-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200911_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizevariations',
            options={'ordering': ('product', 'size__size_order'), 'verbose_name_plural': 'Size Variations'},
        ),
    ]
