# Generated by Django 3.1.1 on 2020-09-13 13:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_shipping_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='fullname',
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
